Repository thoth-station/graph-backup-job, pull requests merged in 2019-11, with the labels that each got.

#1 support from Thoth sourceops services
  .coafile
  .thoth.yaml
  .zuul.yaml
  pyproject.toml
Labels: approved, size/M

#4 application to take backup of db and store to ceph
  Pipfile
  Pipfile.lock
  app.py
Labels: approved, size/XL

#5 openshift template to deploy the cronjob
  openshift/buildConfig-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
Labels: size/L

#7 Add missing import
  app.py
Labels: approved, size/XS

#8 Remove unused variable
  app.py
Labels: approved, size/XS

#9 Do not use timeout in run command
  app.py
Labels: approved, size/XS

#10 Add liveness probe
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#12 Automatic update of dependency thoth-storages from 0.19.24 to 0.19.25
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase, size/L

#14 Automatic update of dependency thoth-analyzer from 0.1.4 to 0.1.5
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase, size/L

#13 Automatic update of dependency thoth-common from 0.9.16 to 0.9.19
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase, size/L
