Repository thoth-station/graph-backup-job, pull requests merged in 2019-12, with the labels that each got.

#16 Automatic update of dependency thoth-common from 0.9.19 to 0.9.20
  Pipfile.lock
Labels: approved, bot, size/M

#17 Automatic update of dependency thoth-common from 0.9.20 to 0.9.21
  Pipfile.lock
Labels: approved, bot, size/M

#18 Automatic update of dependency thoth-analyzer from 0.1.5 to 0.1.6
  Pipfile.lock
Labels: approved, bot, size/M

#21 Automatic update of dependency thoth-storages from 0.19.25 to 0.19.27
  Pipfile.lock
Labels: bot, size/S

#22 thoth-s2i based dockerfile for postgresql
  Dockerfile
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/M

#23 thothTemplate required for thoth advise
  .thoth.yaml
  .thothTemplate.yaml
  openshift/buildConfig-template.yaml
Labels: approved, size/S

#24 Be consistent with the rest of the repos
  .thoth.yaml
  .thothTemplate.yaml
Labels: approved, size/XS

#25 Automatic update of dependency thoth-analyzer from 0.1.6 to 0.1.7
  Pipfile.lock
Labels: approved, bot, size/S

#26 Automatic update of dependency thoth-common from 0.9.21 to 0.9.22
  Pipfile.lock
Labels: approved, bot, size/M

#27 Automatic update of dependency thoth-storages from 0.19.27 to 0.19.30
  Pipfile.lock
Labels: approved, bot, size/M

#30 Set starting deadline seconds to null
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#28 No need to have special SA for this cronjob
  app.py
  openshift/cronJob-template.yaml
Labels: approved, size/M
