Repository thoth-station/graph-backup-job, pull requests merged in 2020-07, with the labels that each got.

#109 Automatic dependency re-locking
  Pipfile.lock
Labels: approved, bot

#110 Automatic update of dependency thoth-storages from 0.22.9 to 0.24.0
  Pipfile.lock
Labels: approved, bot, size/L

#111 Automatic update of dependency thoth-common from 0.13.3 to 0.14.1
  Pipfile.lock
Labels: approved, bot, size/L

#113 Remove OpenShift templates, use Thoth application
  openshift/buildConfig-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/L

#114 Automatic update of dependency thoth-storages from 0.24.0 to 0.24.2
  Pipfile.lock
Labels: approved, bot

#115 Remove latest versions limitation
  .thothTemplate.yaml
Labels: approved, size/XS

#116 Automatic update of dependency thoth-storages from 0.24.2 to 0.24.4
  Pipfile.lock
Labels: approved, bot, size/M

#117 Automatic update of dependency thoth-common from 0.14.1 to 0.14.2
  Pipfile.lock
Labels: approved, bot, size/M

#118 not all updates are required for postgresql10
  Dockerfile
Labels: approved, size/XS

#120 Automatic update of dependency thoth-storages from 0.24.4 to 0.24.5
  Pipfile.lock
Labels: approved, bot

#122 Automatic update of dependency thoth-common from 0.14.2 to 0.15.0
  Pipfile.lock
Labels: approved, bot, size/M
