Repository thoth-station/graph-backup-job, pull requests merged in 2020-03, with the labels that each got.

#85 Automatic update of dependency thoth-common from 0.10.9 to 0.10.11
  Pipfile.lock
Labels: bot, size/M

#86 Automatic update of dependency thoth-common from 0.10.11 to 0.10.12
  Pipfile.lock
Labels: bot, size/M

#87 Automatic update of dependency thoth-storages from 0.22.3 to 0.22.5
  Pipfile.lock
Labels: bot, size/S

#89 Increase memory requirements due to OOM
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#90 Automatic update of dependency thoth-common from 0.10.12 to 0.12.0
  Pipfile.lock
Labels: bot, size/M

#91 Automatic update of dependency thoth-common from 0.12.0 to 0.12.1
  Pipfile.lock
Labels: bot, size/S

#92 Automatic update of dependency thoth-common from 0.12.1 to 0.12.3
  Pipfile.lock
Labels: bot, size/M

#93 Automatic update of dependency thoth-common from 0.12.3 to 0.12.4
  Pipfile.lock
Labels: bot, size/S

#94 Automatic update of dependency thoth-storages from 0.22.5 to 0.22.6
  Pipfile.lock
Labels: bot, size/XS

#95 Automatic update of dependency thoth-storages from 0.22.6 to 0.22.7
  Pipfile.lock
Labels: bot, size/M
