Repository thoth-station/graph-backup-job, pull requests merged in 2020-09, with the labels that each got.

#127 Automatic update of dependency thoth-storages from 0.24.5 to 0.25.5
  Pipfile.lock
Labels: approved, bot, size/L

#129 Split version and component version
  app.py
Labels: approved, size/XS

#131 Automatic update of dependency thoth-common from 0.15.0 to 0.17.2
  Pipfile.lock
Labels: approved, bot

#132 Release of version 0.7.0
  CHANGELOG.md
  app.py
Labels: approved, bot, size/L
