Repository thoth-station/graph-backup-job, pull requests merged in 2022-01, with the labels that each got.

#212 Enable TLS verification
  .thoth.yaml
Labels: approved, size/XS

#214 Remove unused .thothTemplate.yaml
  .thothTemplate.yaml
Labels: approved, size/S

#215 Add metrics about pg dump creation status
  app.py
Labels: size/M, approved
